name: ACAI TERRAFORM MODULE

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  tf_module_checks:
    uses: acai-solutions/github-workflows/.github/workflows/checks-tf-module.yml@aws_esc
    if: ${{ github.event_name == 'pull_request' }}
    with:
      terratest_config_repo_path: 'aws/matrix_tf1x14x0_aws6x0x0.json'
      test_beds: '["AWS_ESC"]'
    secrets: inherit

    
  tf_module_release:
    uses: acai-solutions/github-workflows/.github/workflows/tf-module-release.yml@main
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
