name: ACAI TERRAFORM MODULE

on:
  workflow_dispatch:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  hcl_module_checks:
    uses: acai-solutions/github-workflows/.github/workflows/checks-hcl-module.yml@open_tofu
    if: ${{ github.event_name == 'pull_request' }}
    with:
      gh_wf_config_repo_ref: open_tofu
      hcl_test_beds: '["AWS", "AWS_ESC"]'
      hcl_test_bed_aws_terratest_configs: '["aws/matrix_tf1x5x7_aws5x80x0.json", "aws/matrix_ofu1x6x0_aws5x80x0.json"]'
      hcl_test_bed_aws_esc_terratest_configs: '["aws/matrix_tf1x14x0_aws6x29x0.json", "aws/matrix_ofu1x9x0_aws6x29x0.json"]'
      hcl_terratest_path: "_test/terratest"
      hcl_terratest_examples_path: "_example"
    secrets: inherit

    
  hcl_module_release:
    uses: acai-solutions/github-workflows/.github/workflows/hcl-module-release.yml@open_tofu
    if: ${{ github.event_name == 'push' }}
    secrets: inherit
